services:
  - type: web
    name: axhrd-irt-engine
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    region: singapore
    healthCheckPath: /api/v1/health
    envVars:
      - key: PORT
        value: 8000
